/* Autogenerated by hxtools bin2c */
#ifndef ELECTRICAL_H
#define ELECTRICAL_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_electrical_bmp[446];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* ELECTRICAL_H */
