/* Autogenerated by hxtools bin2c */
#ifndef EXCLAMATION_H
#define EXCLAMATION_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_exclamation_bmp[398];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* EXCLAMATION_H */
