/* Autogenerated by hxtools bin2c */
#ifndef NETWORK_H
#define NETWORK_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_network_bmp[446];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* NETWORK_H */
